### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by mbrgm** [mrVanDalo/terranix#3]
Would you mind adding a license to the project, so people can work (fork etc.) from here in a legally safe way? E.g. [nixpkgs has MIT](https://github.com/NixOS/nixpkgs/blob/master/COPYING).

**Comment by mrVanDalo** [comment]
Good point. Stuff like this slips under my radar usually, thanks.

**Comment by mrVanDalo** [comment]
I put it on GPL-3. Thanks again for the hint.

**Comment by mbrgm** [comment]
@mrVanDalo Doesn't GPL'ing this make it impossible to deploy any infrastructure with terranix without also having to GPL and disclose the full source of that infrastructure setup (which would absolutely outrule it in any corporate context)?

**Comment by mrVanDalo** [comment]
No, this is definitely not true. You can read the GPL it is very short. It states that the licenses stays free even if you ship binaries. It also has a special section for compilers.

> changes to terranix must also be open-sourced, but systems using it as another component in the same way as Nix, NixOS, Terraform.

Systems using it as a component must be also GPL. So if you PUBLISH! a software that builds on terranix, like uses sources from it, not just call the binary. This PUBLISHED! software must be under GPL. There are no license demans on the output you generate with terranix, or on how you create the input files for terranix.
