### ISSUE TITLE
Handling nulls

### ISSUE THREAD

**Issue by manveru** [mrVanDalo/terranix#4]
When using JSON format, some terraform attributes need to be set to null, even when the docs shows as optional
Ref: https://github.com/terraform-providers/terraform-provider-aws/issues/8786#issuecomment-496935442
Terranix strips out null attrs which causes a problem with some resources. An example of it can be found at https://github.com/input-output-hk/perf-ops/blob/master/resources/sg/sg-egress.nix

Right now we work around it by running `sed` on the generated JSON, but I'd love to know if there's a better way to do it.

**Comment by mrVanDalo** [comment]
Oh that is bad to hear, I will have a look at it, but till than it might be a good idea using `jq` instead of `sed`.

**Comment by manveru** [comment]
Yeah, I'm using `terranix | jq 'walk(if . == "null" then null else . end)'`, in case anyone will find this useful.

**Comment by mrVanDalo** [comment]
I was thinking about it this weekend, and there was a problem I had with rendering `null`s, but  I couldn't remember what the problem was exactly. 
I think its best to add an option for *not* stripping the `null`s. I wouldn't enable it by default for now, so other peoples code is not broken by accident.

**Comment by mrVanDalo** [comment]
I just released 2.2.2 which has the `--with-nulls` options. Please let me know if there are any problems with that option. https://github.com/mrVanDalo/terranix/releases/tag/2.2.2

**Comment by mrVanDalo** [comment]
@manveru could you try the new version and check if the `--with-nulls` parameter solved your issues?
I'm closing this ticket. If it don't fixes your issues please reopen this ticket.
